"""
core/integration.py — Desktop integration and wrapper generation.

Call order for a first-time setup:
  1. generate_wrapper()          → creates ~/.local/bin/BeamMP-Helper
  2. generate_desktop_entries()  → creates .desktop files pointing to that wrapper
"""

import os
import sys
from pathlib import Path
import shutil
import subprocess

from beammp_helper.core.config import EXECUTABLE_PATH, save_state

DESKTOP_DIR = Path.home() / ".local" / "share" / "applications"


def generate_wrapper(state: dict) -> bool:
	"""
	Write a portable launcher wrapper to EXECUTABLE_PATH (~/.local/bin/BeamMP-Helper).

	Uses sys.executable (the Python that is running right now) so the wrapper is
	correct whether the user is running from a uv-managed venv, a system pip
	install, or any other Python environment — without hardcoding any paths.

	Returns True on success, False on any OS error.
	"""
	python_exe = sys.executable
	wrapper_content = f"""#!/bin/bash
# BeamMP-Helper launcher — auto-generated by BeamMP-Helper setup.
# Re-run 'BeamMP-Helper tui' and choose desktop integration to regenerate.
exec "{python_exe}" -m beammp_helper "$@"
"""
	try:
		EXECUTABLE_PATH.parent.mkdir(parents=True, exist_ok=True)
		EXECUTABLE_PATH.write_text(wrapper_content, encoding="utf-8")
		os.chmod(EXECUTABLE_PATH, 0o755)
		state["wrapper_installed"] = True
		save_state(state)
		return True
	except OSError:
		return False


def generate_desktop_entries(state: dict) -> bool:
	"""
	Write BeamMP.desktop and BeamMP-Helper.desktop into ~/.local/share/applications/.

	Requires the wrapper to exist first — call generate_wrapper() before this.
	Returns True on success, False if the wrapper is missing or an OS error occurs.
	"""
	if not EXECUTABLE_PATH.exists():
		return False

	exec_path = str(EXECUTABLE_PATH.resolve())

	beammp_content = f"""[Desktop Entry]
Type=Application
Name=BeamMP
Comment=Launch BeamMP for BeamNG.drive
Exec={exec_path} launch
Icon=steam_icon_284160
Terminal=true
Categories=Game;
"""

	helper_content = f"""[Desktop Entry]
Type=Application
Name=BeamMP Helper
Comment=Manage and launch BeamMP on Linux
Exec={exec_path} tui
Terminal=true
Categories=Utility;Settings;
"""

	try:
		DESKTOP_DIR.mkdir(parents=True, exist_ok=True)

		beammp_file = DESKTOP_DIR / "BeamMP.desktop"
		helper_file = DESKTOP_DIR / "BeamMP-Helper.desktop"

		beammp_file.write_text(beammp_content, encoding="utf-8")
		helper_file.write_text(helper_content, encoding="utf-8")

		os.chmod(beammp_file, 0o755)
		os.chmod(helper_file, 0o755)

		update_db = shutil.which("update-desktop-database")
		if update_db:
			subprocess.run([update_db, str(DESKTOP_DIR)], capture_output=True)

		return True
	except OSError:
		return False
